# Generated by Django 5.0 on 2023-12-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='name',
            new_name='crime',
        ),
    ]
